//Playground
#define PLAYGROUND_OFFSET_Y		3
#define PLAYGROUND_OFFSET_X		5
#define PLAYGROUND_BOARDER_COLOR	FARBE_MAGENTA
#define PLAYGROUND_BACKGROUND_COLOR	HINTERGRUND_SCHWARZ

//GAME
#define NUMBER_OF_STREETS	9

#define STREET_FIRST_Y		6
#define STREET_OFFSET		10
#define STREET_VISIBLE		20
#define STREET_LENGTH		STREET_OFFSET+STREET_VISIBLE+STREET_OFFSET

#define GAME_TICK_DURATION_MS	400
#define LIVES				3

//Player
#define PLAYER_XPOS		STREET_OFFSET+STREET_VISIBLE/2+5
#define PLAYER_YPOS		STREET_FIRST_Y+NUMBER_OF_STREETS+2
#define PLAYER_SYMBOL	'P'
#define PLAYER_COLOR	CURSOR_GRUEN

//MOVEMENT
#define PLAYER_UP		'w'
#define PLAYER_LEFT		'a'
#define PLAYER_DOWN		's'
#define PLAYER_RIGHT	'd'

//STREET
#define TRAFFIC_RIGHT	0
#define TRAFFIC_LEFT	1
#define TRAFFIC_PROBABILITY	10
#define MAX_CAR_LENGTH	10

//Scoreboard
#define SCOREBOARD_XPOS	 PLAYGROUND_OFFSET_X + STREET_LENGTH
#define SCOREBOARD_YPOS	 PLAYGROUND_OFFSET_Y + 3

//Movement
#define MOVE_UP		0
#define MOVE_LEFT	1
#define MOVE_DOWN	2
#define MOVE_RIGHT	3



